Each Question is worth 1 point

In [27]:
import numpy as np

1. Create a 3x3 matrix of zeros stored in a variable named zeros and print zeros

In [28]:
# Insert answer here
zeros = np.zeros((3,3))
print(f'Create a 3x3 matrix of zeros,\n{zeros}\n')

Create a 3x3 matrix of zeros,
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



2. Create an array of 10 .1's stored in a variable named tenths and print tenths

In [29]:
# Insert answer here
tenths = (np.ones(10)/10)
print(f'Create an array of 10 0.1\'s,\n{tenths}\n')


Create an array of 10 0.1's,
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]



3. Create an array of the odd number integers from 1 to 15 in a variable named odds and print odds


In [30]:
# Insert answer here
odds = np.arange(1,16,2)
print(f'Create an array of odd integers from 1 to 15,\n{odds}\n')


Create an array of odd integers from 1 to 15,
[ 1  3  5  7  9 11 13 15]



4. Create a 6x6 matrix with values ranging from 1 to 36 in a variable named sixBySix and print sixBySix

In [31]:
# Insert answer here
sixBySix = np.arange(1,37).reshape(6,6)
# sixBySix = sixBySix.reshape(6,6) merged back, with "." method.
print(f'Create a 6x6 matrix, with values ranging from 1 to 36,\n{sixBySix}\n')


Create a 6x6 matrix, with values ranging from 1 to 36,
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]



5. Create a 3x3 identity matrix in a variable named identity and print identity

In [32]:
# Insert answer here
identity = np.eye(3)
print(f'Create a 3x3 identity matrix,\n{identity}\n')


Create a 3x3 identity matrix,
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



6. Create an array of 20 rand integers between 1 and 10 in a variable named twentyRandom and print twentyRandom

In [33]:
# Insert answer here
from numpy.random import randint
# -1 the high value of the np randint is exclusive: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html
#twentyRandom = randint(1,10,20)
twentyRandom = randint(1,11,20)
print(f'Create an array of 20 rand integers between 1 and 10,\n{twentyRandom}\n')


Create an array of 20 rand integers between 1 and 10,
[ 4  9  1  2  8  9  3  4  4  7 10  1 10  1  4  7  2 10  2 10]



7. Create an array of 21 lineraly spaced points between 0 and 5 in a variable called spaced print spaced

In [34]:
# Insert answer here
spaced = np.linspace(0,5,21)
print(f'Create an array of 21 lineraly spaced points between 0 and 5,\n{spaced}\n')


Create an array of 21 lineraly spaced points between 0 and 5,
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]



In [35]:
# The arr array will be used to answer questions 8 through 13
arr = np.arange(1, 51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


8. Use a slice to print the first five elements in the arr array

In [36]:
# Insert answer here
print(f'The base arr array,\n{arr}\n')
print(f'Use a slice to print the first five elements in the arr array, \n{arr[:5]}\n')


The base arr array,
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Use a slice to print the first five elements in the arr array, 
[1 2 3 4 5]



9. Use a slice to print the last fifteen elements in the arr array

In [37]:
# Insert answer here
print(f'The base arr array,\n{arr}\n')
print(f'Use a slice to print the last fifteen elements in the arr array. \n{arr[-15:]}\n')


The base arr array,
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Use a slice to print the last fifteen elements in the arr array. 
[36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]



10. Use a slice to print the values from 20 through 30 in the arr array

In [38]:
# Insert answer here
print(f'The base arr array,\n{arr}\n')
print(f'Use a slice to print the values from 20 through 30 in the arr array,\n{arr[19:30]}\n')


The base arr array,
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Use a slice to print the values from 20 through 30 in the arr array,
[20 21 22 23 24 25 26 27 28 29 30]



11. Print the values that are > 43 in the arr array using conditional selection

In [39]:
# Insert answer here
print(f'The base arr array,\n{arr}\n')
print(f'Print the values that are > 43 in the arr array using conditional selection,\n{arr[arr>43]}\n')


The base arr array,
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Print the values that are > 43 in the arr array using conditional selection,
[44 45 46 47 48 49 50]



12. Print the values that are <= 12 in the arr array using conditional selection

In [40]:
# Insert answer here
print(f'The base arr array,\n{arr}\n')
print(f'Print the values that are <= 12 in the arr array using conditional selection,\n{arr[arr<=12]}\n')


The base arr array,
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Print the values that are <= 12 in the arr array using conditional selection,
[ 1  2  3  4  5  6  7  8  9 10 11 12]



13. Print the sum of the arr array

In [41]:
# Insert answer here
print(f'The base arr array,\n{arr}\n')
print(f'Print the sum of the arr array,\n{np.sum(arr)}\n')


The base arr array,
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Print the sum of the arr array,
1275



In [42]:
# The twentyRandom array will be used to answer question 14
twentyRandom = np.random.randint(1,201,20)
print(twentyRandom)

[ 77 170 150  73  21 123 128  86 141  29  12 131 192  16 126 155   6 106
   7   9]


14. Print the argument of the min value and max value in the twentyRandom array

In [43]:
# Insert answer here
print(f'The base twentyRandom array,\n{twentyRandom}\n')
print(f'The argument position for the minimum value is, {twentyRandom.argmin()}')
print(f'The minimum value is, {twentyRandom.min()}, and it is at index, {twentyRandom.argmin()}')
print(f'The argument position for the maximum value is, {twentyRandom.argmax()}')
print(f'The maximum value is, {twentyRandom.max()}, and it is at index, {twentyRandom.argmax()}')


The base twentyRandom array,
[ 77 170 150  73  21 123 128  86 141  29  12 131 192  16 126 155   6 106
   7   9]

The argument position for the minimum value is, 16
The minimum value is, 6, and it is at index, 16
The argument position for the maximum value is, 12
The maximum value is, 192, and it is at index, 12


In [44]:
# The arr_2d array will be used to answer questions 15 and 16
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60]])
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]]


15. Using single bracket notation get and print 40

In [45]:
# Insert answer here
print(f'The base 2 dimension array is,\n{arr_2d}\n')
print(f'Using single bracket notation get and print 40,\n{arr_2d[2,1]}\n')


The base 2 dimension array is,
[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]]

Using single bracket notation get and print 40,
40



16. Using single bracket notation get and print the following chunk from arr_2d:
    [[25 30]
     [40 45]
     [55 60]]

In [46]:
# Insert answer here
print(f'The base 2 dimension array is,\n{arr_2d}\n')
print(f'Using single bracket notation get and print the following chunk from arr_2d: [[25 30] [40 45] [55 60]],\n{arr_2d[1:4,1:3]}\n')


The base 2 dimension array is,
[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]]

Using single bracket notation get and print the following chunk from arr_2d: [[25 30] [40 45] [55 60]],
[[25 30]
 [40 45]
 [55 60]]



In [47]:
# The arrOne array will be used to answer questions 17 through 20
arrOne = np.arange(1,11)
print(arrOne)

[ 1  2  3  4  5  6  7  8  9 10]


17. Add three to each of the elements in the arrOne array and print the updated arrOne array. Do not update the arrOne array in memory.

In [48]:
# Insert answer here
print(f'The base arrOne array,\n{arrOne}\n')
print(f'Add three to each of the elements in the arrOne array and print the updated arrOne array,\n{arrOne + 3}\n')
print(f'Show the non-updated arrOne array,\n{arrOne}\n')


The base arrOne array,
[ 1  2  3  4  5  6  7  8  9 10]

Add three to each of the elements in the arrOne array and print the updated arrOne array,
[ 4  5  6  7  8  9 10 11 12 13]

Show the non-updated arrOne array,
[ 1  2  3  4  5  6  7  8  9 10]



18. Calculate and print the square of each element in the arrOne array, make sure and use the appropriate NumPy method to calculate the square. Do not update the arrOne array in memory.

In [49]:
# Insert answer here
print(f'The base arrOne array,\n{arrOne}\n')
# -.5 did not use the NumPy square method
#print(f'Calculate and print the square of each element in the arrOne array, make sure and use the appropriate NumPy method,\n{arrOne ** 2}\n')
print(f'Calculate and print the square of each element in the arrOne array, make sure and use the appropriate NumPy method,\n{np.square(arrOne)}\n')
print(f'Show the non-updated arrOne array,\n{arrOne}\n')


The base arrOne array,
[ 1  2  3  4  5  6  7  8  9 10]

Calculate and print the square of each element in the arrOne array, make sure and use the appropriate NumPy method,
[  1   4   9  16  25  36  49  64  81 100]

Show the non-updated arrOne array,
[ 1  2  3  4  5  6  7  8  9 10]



19. Use broadcasting to change the first four elements in the arrOne array to -999 and print the updated array.

In [50]:
# Insert answer here
print(f'The base arrOne array,\n{arrOne}\n')
# -1 only the first 3 elements were changed
arrOne[:3] = -999
print(f'Use broadcasting to change the first four elements in the arrOne array to -999 and print the updated array,\n{arrOne}\n')


The base arrOne array,
[ 1  2  3  4  5  6  7  8  9 10]

Use broadcasting to change the first four elements in the arrOne array to -999 and print the updated array,
[-999 -999 -999    4    5    6    7    8    9   10]



In [52]:
# Insert answer here
arrOne = np.arange(1,11)
print(f'The base arrOne array,\n{arrOne}\n')
arrOne[:4] = -999
print(f'Use broadcasting to change the first four elements in the arrOne array to -999 and print the updated array,\n{arrOne}\n')


The base arrOne array,
[ 1  2  3  4  5  6  7  8  9 10]

Use broadcasting to change the first four elements in the arrOne array to -999 and print the updated array,
[-999 -999 -999 -999    5    6    7    8    9   10]



20. Print out the absolute value of each element in arrOne. Do not update the arrOne array in memory.

In [53]:
# Insert answer here
print(f'The new base arrOne array,\n{arrOne}\n')
print(f'Print out the absolute value of each element in arrOne,\n{np.abs(arrOne)}\n')
print(f'Show the non-updated new base arrOne array,\n{arrOne}\n')


The new base arrOne array,
[-999 -999 -999 -999    5    6    7    8    9   10]

Print out the absolute value of each element in arrOne,
[999 999 999 999   5   6   7   8   9  10]

Show the non-updated new base arrOne array,
[-999 -999 -999 -999    5    6    7    8    9   10]



## End of coding for Jonathan Heard