Each Question is worth 1 point

In [1]:
import numpy as np

1. Create a 3x3 matrix of zeros stored in a variable named zeros and print zeros

In [2]:
# Insert answer here
zeros = np.zeros((3,3))
print(f'A 3x3 matrix of zeros,\n {zeros}')

A 3x3 matrix of zeros,
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2. Create an array of 10 .1's stored in a variable named tenths and print tenths

In [3]:
# Insert answer here
tenths = (np.ones(10)/10)
print(f'An array of 10 0.1\'s,\n {tenths}')


An array of 10 0.1's,
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]


3. Create an array of the odd number integers from 1 to 15 in a variable named odds and print odds


In [4]:
# Insert answer here
odds = np.arange(1,16,2)
print(f'An array of odd integers from 1 to 15,\n {odds}')


An array of odd integers from 1 to 15,
 [ 1  3  5  7  9 11 13 15]


4. Create a 6x6 matrix with values ranging from 1 to 36 in a variable named sixBySix and print sixBySix

In [5]:
# Insert answer here
sixBySix = np.arange(1,37).reshape(6,6)
# sixBySix = sixBySix.reshape(6,6) merged back, with "." method.
print(f'A 6x6 matrix, with values ranging from 1 to 36,\n{sixBySix}')


A 6x6 matrix, with values ranging from 1 to 36,
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


5. Create a 3x3 identity matrix in a variable named identity and print identity

In [6]:
# Insert answer here
identity = np.eye(3)
print(f'A 3x3 identity matrix,\n{identity}')


A 3x3 identity matrix,
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


6. Create an array of 20 rand integers between 1 and 10 in a variable named twentyRandom and print twentyRandom

In [7]:
# Insert answer here
from numpy.random import randint
twentyRandom = randint(1,10,20)
print(f'An array of 20 rand integers between 1 and 10,\n{twentyRandom}')


An array of 20 rand integers between 1 and 10,
[9 7 5 1 3 8 3 5 4 4 8 9 8 6 3 8 6 4 3 7]


7. Create an array of 21 lineraly spaced points between 0 and 5 in a variable called spaced print spaced

In [8]:
# Insert answer here
spaced = np.linspace(0,5,21)
print(f'An array of 21 lineraly spaced points between 0 and 5,\n{spaced}\n')


An array of 21 lineraly spaced points between 0 and 5,
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]



In [9]:
# The arr array will be used to answer questions 8 through 13
arr = np.arange(1, 51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


8. Use a slice to print the first five elements in the arr array

In [10]:
# Insert answer here
print(f'The base arr array,\n{arr}\n')
print(f'Use a slice to print the first five elements in the arr array, \n{arr[:5]}')


The base arr array,
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Use a slice to print the first five elements in the arr array, 
[1 2 3 4 5]


9. Use a slice to print the last fifteen elements in the arr array

In [11]:
# Insert answer here
print(f'The base arr array,\n{arr}\n')
print(f'Use a slice to print the last fifteen elements in the arr array. \n{arr[-15:]}')


The base arr array,
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Use a slice to print the last fifteen elements in the arr array. 
[36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


10. Use a slice to print the values from 20 through 30 in the arr array

In [12]:
# Insert answer here
print(f'The base arr array,\n{arr}\n')
print(f'Use a slice to print the values from 20 through 30 in the arr array,\n{arr[19:30]}')


The base arr array,
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Use a slice to print the values from 20 through 30 in the arr array,
[20 21 22 23 24 25 26 27 28 29 30]


11. Print the values that are > 43 in the arr array using conditional selection

In [13]:
# Insert answer here
print(f'The base arr array,\n{arr}\n')
print(f'Print the values that are > 43 in the arr array using conditional selection,\n{arr[arr>43]}')


The base arr array,
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Print the values that are > 43 in the arr array using conditional selection,
[44 45 46 47 48 49 50]


12. Print the values that are <= 12 in the arr array using conditional selection

In [14]:
# Insert answer here
print(f'The base arr array,\n{arr}\n')
print(f'Print the values that are <= 12 in the arr array using conditional selection,\n{arr[arr<=12]}')


The base arr array,
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Print the values that are <= 12 in the arr array using conditional selection,
[ 1  2  3  4  5  6  7  8  9 10 11 12]


13. Print the sum of the arr array

In [15]:
# Insert answer here
print(f'The base arr array,\n{arr}\n')
print(f'Print the sum of the arr array,\n{np.sum(arr)}')


The base arr array,
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Print the sum of the arr array,
1275


In [16]:
# The twentyRandom array will be used to answer question 14
twentyRandom = np.random.randint(1,201,20)
print(twentyRandom)

[ 47 179  55  50  26   8  98 101  14  87 116  98 199  64  12 109 154 126
  90  57]


14. Print the argument of the min value and max value in the twentyRandom array

In [17]:
# Insert answer here

In [18]:
# The arr_2d array will be used to answer questions 15 and 16
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60]])
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]]


15. Using single bracket notation get and print 40

In [19]:
# Insert answer here

16. Using single bracket notation get and print the following chunk from arr_2d:
    [[25 30]
     [40 45]
     [55 60]]

In [20]:
# Insert answer here

In [21]:
# The arrOne array will be used to answer questions 17 through 20
arrOne = np.arange(1,11)
print(arrOne)

[ 1  2  3  4  5  6  7  8  9 10]


17. Add three to each of the elements in the arrOne array and print the updated arrOne array. Do not update the arrOne array in memory.

In [22]:
# Insert answer here

18. Calculate and print the square of each element in the arrOne array, make sure and use the appropriate NumPy method to calculate the square. Do not update the arrOne array in memory.

In [23]:
# Insert answer here

19. Use broadcasting to change the first four elements in the arrOne array to -999 and print the updated array.

In [24]:
# Insert answer here

20. Print out the absolute value of each element in arrOne. Do not update the arrOne array in memory.

In [25]:
# Insert answer here