Each Question is worth 1 point

In [1]:
import numpy as np

1. Create a 3x3 matrix of zeros stored in a variable named zeros and print zeros

In [2]:
# Insert answer here
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

2. Create an array of 10 .1's stored in a variable named tenths and print tenths

In [3]:
# Insert answer here
tenths = np.ones(10)
tenths

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

3. Create an array of the odd number integers from 1 to 15 in a variable named odds and print odds


In [4]:
# Insert answer here

4. Create a 6x6 matrix with values ranging from 1 to 36 in a variable named sixBySix and print sixBySix

In [5]:
# Insert answer here

5. Create a 3x3 identity matrix in a variable named identity and print identity

In [6]:
# Insert answer here

6. Create an array of 20 rand integers between 1 and 10 in a variable named twentyRandom and print twentyRandom

In [7]:
# Insert answer here

7. Create an array of 21 lineraly spaced points between 0 and 5 in a variable called spaced print spaced

In [8]:
# Insert answer here

In [9]:
# The arr array will be used to answer questions 8 through 13
arr = np.arange(1, 51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


8. Use a slice to print the first five elements in the arr array

In [10]:
# Insert answer here

9. Use a slice to print the last fifteen elements in the arr array

In [11]:
# Insert answer here

10. Use a slice to print the values from 20 through 30 in the arr array

In [12]:
# Insert answer here

11. Print the values that are > 43 in the arr array using conditional selection

In [13]:
# Insert answer here

12. Print the values that are <= 12 in the arr array using conditional selection

In [14]:
# Insert answer here

13. Print the sum of the arr array

In [15]:
# Insert answer here

In [16]:
# The twentyRandom array will be used to answer question 14
twentyRandom = np.random.randint(1,201,20)
print(twentyRandom)

[ 73  56 108  21  18 113 154  23  80  84 177 197  48   2  46 195  82  52
  79 184]


14. Print the argument of the min value and max value in the twentyRandom array

In [17]:
# Insert answer here

In [18]:
# The arr_2d array will be used to answer questions 15 and 16
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60]])
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]]


15. Using single bracket notation get and print 40

In [19]:
# Insert answer here

16. Using single bracket notation get and print the following chunk from arr_2d:
    [[25 30]
     [40 45]
     [55 60]]

In [20]:
# Insert answer here

In [21]:
# The arrOne array will be used to answer questions 17 through 20
arrOne = np.arange(1,11)
print(arrOne)

[ 1  2  3  4  5  6  7  8  9 10]


17. Add three to each of the elements in the arrOne array and print the updated arrOne array. Do not update the arrOne array in memory.

In [22]:
# Insert answer here

18. Calculate and print the square of each element in the arrOne array, make sure and use the appropriate NumPy method to calculate the square. Do not update the arrOne array in memory.

In [23]:
# Insert answer here

19. Use broadcasting to change the first four elements in the arrOne array to -999 and print the updated array.

In [24]:
# Insert answer here

20. Print out the absolute value of each element in arrOne. Do not update the arrOne array in memory.

In [25]:
# Insert answer here